name: Convert Images to WebP

on:
  push:
    paths:
      - 'images/**'
      - '.github/workflows/convert-pictures-to-webp.yml'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg

    - name: Convert images to webp
      run: |
        find images/ -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.svg' \) -print0 | \
        while IFS= read -r -d '' file; do
          ffmpeg -i "$file" "${file%.*}.webp" && rm "$file"
        done

    - name: Check for changes and push
      id: git_diff
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m 'Convert images to webp format and remove original images'
          git push
        else
          echo "No changes to commit"
        fi
